"""empty message

Revision ID: 5aa499bda58e
Revises: d18da4011141
Create Date: 2022-06-14 11:51:58.182892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa499bda58e'
down_revision = 'd18da4011141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'artist_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('show', 'venue_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('show', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=False) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'start_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('show', 'venue_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('show', 'artist_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
