"""empty message

Revision ID: 652c1f7a711f
Revises: cf13216a45f0
Create Date: 2022-06-12 09:53:50.301713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652c1f7a711f'
down_revision = 'cf13216a45f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_for_show', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show', 'venue', ['venue_for_show'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'venue_for_show')
    # ### end Alembic commands ###
