"""empty message

Revision ID: cf13216a45f0
Revises: a52f3db4db38
Create Date: 2022-06-11 15:18:20.686061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf13216a45f0'
down_revision = 'a52f3db4db38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('performing_artist', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show', 'artist', ['performing_artist'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'performing_artist')
    # ### end Alembic commands ###
